package com.sales.services;

import java.util.ArrayList;

import org.springframework.beans.factory.annotation.Autowired;

import com.sales.models.Book;
import com.sales.services.BookService;

public class BookService {
	
	@Autowired // This means to get the bean called shipInterface, Which is auto-generated by Spring, we will use it to handle the data
	private ShipInterface shipInterface;
	
	public ArrayList<Ship> listAll()
	{
		// Find all elements in the 'Ship' table and put them in an ArrayList called 'ships', then return the Ship arrayList
		return (ArrayList<Ship>) shipInterface.findAll();
	}
	
	public Ship addShip(Ship ship) 
	{
		return shipInterface.save(ship);
	}

}
