package com.sales.services;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;

import org.springframework.beans.factory.annotation.Autowired;

import com.sales.models.Book;
import com.sales.models.Loan;
import com.sales.repositories.BookInterface;
import com.sales.repositories.CustomerInterface;
import com.sales.repositories.LoanInterface;



public class LoanService {
	
	@Autowired // This means to get the bean called OrderInterface, Which is auto-generated by Spring, we will use it to handle the data
	private LoanInterface loanInterface;

	@Autowired // This means to get the bean called OrderInterface, Which is auto-generated by Spring, we will use it to handle the data
	private BookInterface bookInterface;
	
	@Autowired // This means to get the bean called OrderInterface, Which is auto-generated by Spring, we will use it to handle the data
	//Gonna be library interface
	private CustomerInterface customerInterface;
	
	@Autowired
	private CustomerService customerService;
	private Book book;
	private Loan loan;
	
	//Set up date formatting for the loan
	private DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
	private Date date = new Date();
	
	public ArrayList<Loan> listAll()
	{
		// Find all elements in the 'Ship' table and put them in an ArrayList called 'ships', then return the Ship arrayList
		return (ArrayList<Loan>) loanInterface.findAll();
	}
	


}
