package com.sales.services;

import org.springframework.beans.factory.annotation.Autowired;

import com.sales.repositories.BookInterface;
import com.sales.repositories.CustomerInterface;
import com.sales.repositories.LoanInterface;


public class LoanService {
	
	@Autowired // This means to get the bean called OrderInterface, Which is auto-generated by Spring, we will use it to handle the data
	private LoanInterface loanInterface;

	@Autowired // This means to get the bean called OrderInterface, Which is auto-generated by Spring, we will use it to handle the data
	private BookInterface bookInterface;
	
	@Autowired // This means to get the bean called OrderInterface, Which is auto-generated by Spring, we will use it to handle the data
	//Gonna be library interface
	private CustomerInterface customerInterface;


}
